// 平台特定的发布设置类型定义

// 长图文平台（文章/长文）
export type LongTextPlatform = 'wechat' | 'zhihu' | 'juejin' | 'zsxq';

// 短图文平台（短文案/配图）
export type ShortTextPlatform =
  | 'wechat_xiaolushu'
  | 'xiaohongshu_note'
  | 'weibo'
  | 'jike'
  | 'x'
  | 'linkedin';

// 文本平台（长图文 + 短图文）
export type TextPlatform = LongTextPlatform | ShortTextPlatform;
// 视频平台
export type VideoPlatform = 'video_wechat' | 'douyin' | 'bilibili' | 'xiaohongshu' | 'youtube';
// 所有平台
export type Platform = TextPlatform | VideoPlatform;

// 基础发布设置
export interface BasePlatformSettings {
  id: string;
  name: string;
  platform: Platform;
  isDefault?: boolean;
  authorName?: string;
  autoGenerateDigest?: boolean;
  headerContent?: string;
  footerContent?: string;
}

// 视频平台特有设置
export interface VideoSettings {
  speechScript?: string;        // 口播稿
  videoTitle?: string;          // 视频标题
  videoDescription?: string;    // 视频描述
  videoTags?: string[];        // 视频标签
  coverImage?: string;         // 默认封面图片（Base64 data URL）
  coverImage169?: string;      // 16:9 封面
  coverImage43?: string;       // 4:3 封面
  platformTips?: string[];     // 平台特定建议
}

// 平台特定配置（暂时保持简单，只有基础字段）
export interface PlatformConfig {
  // 预留给未来扩展的平台特定字段
  [key: string]: any;
}

// 完整的平台设置
export interface PlatformSettings extends BasePlatformSettings {
  platformConfig?: PlatformConfig;
  // 如果是视频平台，包含视频特有设置
  videoSettings?: VideoSettings;
}

// 简化的平台特定设置类型
export interface WechatSettings extends BasePlatformSettings {
  platform: 'wechat';
}

export interface WechatXiaolushuSettings extends BasePlatformSettings {
  platform: 'wechat_xiaolushu';
}

export interface ZhihuSettings extends BasePlatformSettings {
  platform: 'zhihu';
}

export interface JuejinSettings extends BasePlatformSettings {
  platform: 'juejin';
}

export interface ZsxqSettings extends BasePlatformSettings {
  platform: 'zsxq';
  groupIds?: string[]; // 知识星球ID列表，支持多个星球
}

// 短图文平台设置
export interface XiaohongshuSettings extends BasePlatformSettings {
  platform: 'xiaohongshu';
}

export interface XiaohongshuNoteSettings extends BasePlatformSettings {
  platform: 'xiaohongshu_note';
}

export interface WeiboSettings extends BasePlatformSettings {
  platform: 'weibo';
}

export interface JikeSettings extends BasePlatformSettings {
  platform: 'jike';
}

export interface XSettings extends BasePlatformSettings {
  platform: 'x';
}

export interface LinkedInSettings extends BasePlatformSettings {
  platform: 'linkedin';
}

// 视频平台设置
export interface VideoWechatSettings extends BasePlatformSettings {
  platform: 'video_wechat';
}

export interface DouyinSettings extends BasePlatformSettings {
  platform: 'douyin';
}

export interface BilibiliSettings extends BasePlatformSettings {
  platform: 'bilibili';
}

export interface YouTubeSettings extends BasePlatformSettings {
  platform: 'youtube';
}

// 平台信息
export interface PlatformInfo {
  id: Platform;
  name: string;
  icon: string;
  color: string;
  description: string;
  supportedFeatures: string[];
}

// 平台配置映射
export const PLATFORM_CONFIGS: Record<Platform, PlatformInfo> = {
  wechat: {
    id: 'wechat',
    name: '微信公众号',
    icon: '📱',
    color: 'bg-green-500',
    description: '微信公众号文章发布',
    supportedFeatures: ['原创标记', '赞赏功能', '留言功能', '精选文章', '定制卡片']
  },
  wechat_xiaolushu: {
    id: 'wechat_xiaolushu',
    name: '小绿书',
    icon: '🟢',
    color: 'bg-emerald-600',
    description: '微信小绿书发布（与公众号同编辑器）',
    supportedFeatures: ['标题（可选）', '短图文正文', '配图上传']
  },
  zhihu: {
    id: 'zhihu',
    name: '知乎',
    icon: '🔵',
    color: 'bg-blue-500',
    description: '知乎专栏文章发布',
    supportedFeatures: ['专栏选择', '标签设置', '话题关联', '评论设置']
  },
  juejin: {
    id: 'juejin',
    name: '掘金',
    icon: '⚡',
    color: 'bg-cyan-500',
    description: '掘金技术文章发布',
    supportedFeatures: ['分类选择', '标签设置', '难度等级', '封面图片']
  },
  zsxq: {
    id: 'zsxq',
    name: '知识星球',
    icon: '🌟',
    color: 'bg-yellow-500',
    description: '知识星球文章和主题发布',
    supportedFeatures: ['多星球发布', '富文本编辑', 'Markdown支持', '文章模式', '主题模式']
  },
  // 短图文平台
  xiaohongshu_note: {
    id: 'xiaohongshu_note',
    name: '小红书（图文）',
    icon: '📕',
    color: 'bg-red-500',
    description: '小红书图文笔记发布',
    supportedFeatures: ['标题优化', '正文填充', '话题标签', '互动引导']
  },
  weibo: {
    id: 'weibo',
    name: '微博',
    icon: '🧣',
    color: 'bg-red-600',
    description: '微博短内容发布',
    supportedFeatures: ['短文案', '话题标签', '链接引导']
  },
  jike: {
    id: 'jike',
    name: '即刻',
    icon: '🟡',
    color: 'bg-yellow-500',
    description: '即刻动态发布',
    supportedFeatures: ['短文案', '话题标签', '链接引导']
  },
  x: {
    id: 'x',
    name: 'X',
    icon: '𝕏',
    color: 'bg-black',
    description: 'X（Twitter）短帖发布',
    supportedFeatures: ['短文案', '线程拆分（规划）', '标签建议（规划）']
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: '💼',
    color: 'bg-blue-700',
    description: 'LinkedIn 职业动态发布',
    supportedFeatures: ['短文案', '话题标签', '链接预览']
  },
  video_wechat: {
    id: 'video_wechat',
    name: '视频号',
    icon: '📹',
    color: 'bg-green-600',
    description: '微信视频号发布',
    supportedFeatures: ['口播稿转换', '短标题生成', '话题标签', '位置信息', '合集管理']
  },
  douyin: {
    id: 'douyin',
    name: '抖音',
    icon: '🎵',
    color: 'bg-black',
    description: '抖音短视频发布',
    supportedFeatures: ['爆款标题', '热门标签', '音乐推荐', '封面建议', '发布时机']
  },
  bilibili: {
    id: 'bilibili',
    name: 'B站',
    icon: '📺',
    color: 'bg-pink-500',
    description: 'B站视频投稿',
    supportedFeatures: ['分区选择', '标签优化', '封面设计', '简介撰写', '投稿声明']
  },
  xiaohongshu: {
    id: 'xiaohongshu',
    name: '小红书（视频）',
    icon: '📕',
    color: 'bg-red-600',
    description: '小红书视频发布',
    supportedFeatures: ['视频标题', '视频描述', '话题标签', '封面建议']
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    icon: '🎬',
    color: 'bg-red-600',
    description: 'YouTube 视频发布',
    supportedFeatures: ['标题优化', '简介撰写', '标签建议', '封面建议', 'SEO关键词']
  }
};

// 平台类型判断工具函数
export function isVideoPlatform(platform: Platform): platform is VideoPlatform {
  return ['video_wechat', 'douyin', 'bilibili', 'xiaohongshu', 'youtube'].includes(platform as VideoPlatform);
}

export function isLongTextPlatform(platform: Platform): platform is LongTextPlatform {
  return ['wechat', 'zhihu', 'juejin', 'zsxq'].includes(platform as LongTextPlatform);
}

export function isShortTextPlatform(platform: Platform): platform is ShortTextPlatform {
  return ['wechat_xiaolushu', 'xiaohongshu_note', 'weibo', 'jike', 'x', 'linkedin'].includes(platform as ShortTextPlatform);
}

export function isTextPlatform(platform: Platform): platform is TextPlatform {
  return !isVideoPlatform(platform);
}

// 获取平台类型
export function getPlatformType(platform: Platform): 'long_text' | 'short_text' | 'video' {
  if (isVideoPlatform(platform)) return 'video';
  return isLongTextPlatform(platform) ? 'long_text' : 'short_text';
}

// 获取平台默认配置（暂时返回空对象，未来扩展时添加平台特定字段）
export function getDefaultPlatformConfig(platform: Platform): PlatformConfig {
  return {};
}
