'use client';

import { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { ArrowLeft, Save } from 'lucide-react';
import { Breadcrumb } from '@/components/ui/breadcrumb';
import { MarkdownEditor } from '@/components/ui/markdown-editor';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

interface PresetForm {
  name: string;
  authorName: string;
  autoGenerateDigest: boolean;
  headerContent: string;
  footerContent: string;
  isDefault: boolean;
}

export default function EditPresetPage() {
  const router = useRouter();
  const params = useParams();
  const presetId = params.id as string;

  const [loading, setLoading] = useState(false);
  const [initialLoading, setInitialLoading] = useState(true);
  const [error, setError] = useState('');
  const [form, setForm] = useState<PresetForm>({
    name: '',
    authorName: '',
    autoGenerateDigest: true,
    headerContent: '',
    footerContent: '',
    isDefault: false,
  });

  useEffect(() => {
    fetchPreset();
  }, [presetId]);

  const fetchPreset = async () => {
    try {
      setInitialLoading(true);
      const response = await fetch(`/api/presets/${presetId}`);
      const data = await response.json();

      if (data.success) {
        const preset = data.data;
        setForm({
          name: preset.name || '',
          authorName: preset.authorName || '',
          autoGenerateDigest: preset.autoGenerateDigest ?? true,
          headerContent: preset.headerContent || '',
          footerContent: preset.footerContent || '',
          isDefault: preset.isDefault ?? false,
        });
      } else {
        setError(data.error || '获取预设失败');
      }
    } catch (error) {
      console.error('获取预设失败:', error);
      setError('获取预设失败');
    } finally {
      setInitialLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!form.name.trim()) {
      setError('请输入预设名称');
      return;
    }

    try {
      setLoading(true);
      setError('');

      const response = await fetch(`/api/presets/${presetId}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(form),
      });

      const data = await response.json();

      if (data.success) {
        router.push('/dashboard/presets');
      } else {
        setError(data.error || '更新预设失败');
      }
    } catch (error) {
      console.error('更新预设失败:', error);
      setError('更新预设失败');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (field: keyof PresetForm, value: string | boolean) => {
    setForm(prev => ({
      ...prev,
      [field]: value,
    }));
  };

  if (initialLoading) {
    return (
      <div className="min-h-screen bg-[#020617] flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
          <p className="mt-4 text-zinc-400">加载中...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#020617] text-zinc-200">
      <div className="max-w-3xl mx-auto py-8 px-4">
        {/* 面包屑导航 */}
        <Breadcrumb
          items={[
            { label: '发布预设', href: '/dashboard/presets' },
            { label: '编辑预设' }
          ]}
          className="mb-6 text-zinc-400"
        />

        {/* 页面标题 */}
        <div className="flex items-center gap-4 mb-8">
          <button
            onClick={() => router.push('/dashboard/presets')}
            className="p-2 text-zinc-400 hover:text-white transition-colors hover:bg-white/10 rounded-lg"
            title="返回预设管理"
          >
            <ArrowLeft className="w-6 h-6" />
          </button>
          <div>
            <h1 className="text-3xl font-bold text-white">编辑发布预设</h1>
            <p className="mt-2 text-zinc-400">修改预设模板配置</p>
          </div>
        </div>

        {/* 错误提示 */}
        {error && (
          <div className="mb-6 p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
            <p className="text-red-400">{error}</p>
          </div>
        )}

        {/* 表单 */}
        <form onSubmit={handleSubmit} className="bg-white/5 backdrop-blur-md rounded-2xl border border-white/10 p-6 md:p-8 shadow-xl">
          <div className="space-y-8">
            {/* 基本信息 */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4 border-b border-white/10 pb-2">基本信息</h3>
              <div className="space-y-5">
                <div>
                  <Label className="text-zinc-300 mb-2 block">
                    预设名称 <span className="text-red-400">*</span>
                  </Label>
                  <Input
                    type="text"
                    value={form.name}
                    onChange={(e) => handleInputChange('name', e.target.value)}
                    placeholder="例如：技术文章预设"
                    className="bg-black/20 border-white/10 text-white placeholder:text-zinc-600 focus-visible:ring-primary/50"
                    required
                  />
                </div>

                <div>
                  <Label className="text-zinc-300 mb-2 block">
                    作者名称
                  </Label>
                  <Input
                    type="text"
                    value={form.authorName}
                    onChange={(e) => handleInputChange('authorName', e.target.value)}
                    placeholder="例如：孟健"
                    className="bg-black/20 border-white/10 text-white placeholder:text-zinc-600 focus-visible:ring-primary/50"
                  />
                </div>
              </div>
            </div>

            {/* 发布设置 */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4 border-b border-white/10 pb-2">发布设置</h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between p-3 rounded-xl bg-white/[0.02] border border-white/5 hover:border-white/10 transition-colors">
                  <div className="flex items-center gap-3">
                    <input
                      type="checkbox"
                      id="autoGenerateDigest"
                      checked={form.autoGenerateDigest}
                      onChange={(e) => handleInputChange('autoGenerateDigest', e.target.checked)}
                      className="h-5 w-5 text-primary rounded border-white/20 bg-white/10 focus:ring-primary/50"
                    />
                    <div>
                      <label htmlFor="autoGenerateDigest" className="block text-sm font-medium text-zinc-200 cursor-pointer">
                        自动生成摘要
                      </label>
                      <p className="text-xs text-zinc-500 mt-1">插件会自动提取正文前120个字符作为摘要</p>
                    </div>
                  </div>
                </div>

              </div>
            </div>

            {/* 内容定制设置 */}
            <div>
              <h3 className="text-lg font-semibold text-white mb-4 border-b border-white/10 pb-2">内容定制设置</h3>

              <div className="space-y-6">
                {/* 开头定制内容 */}
                <MarkdownEditor
                  label="开头定制内容"
                  value={form.headerContent}
                  onChange={(value) => handleInputChange('headerContent', value)}
                  placeholder="在文章开头插入的内容，支持Markdown语法..."
                  className="mt-2"
                />

                {/* 末尾定制内容 */}
                <MarkdownEditor
                  label="末尾定制内容"
                  value={form.footerContent}
                  onChange={(value) => handleInputChange('footerContent', value)}
                  placeholder="在文章末尾插入的内容，支持Markdown语法..."
                  className="mt-2"
                />
              </div>
            </div>
          </div>

          {/* 提交按钮 */}
          <div className="mt-8 flex justify-end gap-3 border-t border-white/10 pt-6">
            <Button
              type="button"
              variant="outline"
              onClick={() => router.push('/dashboard/presets')}
              className="bg-white/5 text-zinc-300 border-white/10 hover:bg-white/10 hover:text-white"
            >
              取消
            </Button>
            <Button
              type="submit"
              disabled={loading}
              className="bg-primary hover:bg-primary/90 text-white shadow-lg shadow-primary/20"
            >
              {loading ? (
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
              ) : (
                <Save className="w-4 h-4 mr-2" />
              )}
              {loading ? '保存中...' : '保存更改'}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}
